//go:build !ignore_autogenerated

/*
Copyright 2021 Syntasso.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentProposal) DeepCopyInto(out *AgentProposal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentProposal.
func (in *AgentProposal) DeepCopy() *AgentProposal {
	if in == nil {
		return nil
	}
	out := new(AgentProposal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentProposal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentProposalEvidence) DeepCopyInto(out *AgentProposalEvidence) {
	*out = *in
	if in.CorrelationIDs != nil {
		in, out := &in.CorrelationIDs, &out.CorrelationIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Since != nil {
		in, out := &in.Since, &out.Since
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentProposalEvidence.
func (in *AgentProposalEvidence) DeepCopy() *AgentProposalEvidence {
	if in == nil {
		return nil
	}
	out := new(AgentProposalEvidence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentProposalList) DeepCopyInto(out *AgentProposalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentProposal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentProposalList.
func (in *AgentProposalList) DeepCopy() *AgentProposalList {
	if in == nil {
		return nil
	}
	out := new(AgentProposalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentProposalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentProposalPlan) DeepCopyInto(out *AgentProposalPlan) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentProposalPlan.
func (in *AgentProposalPlan) DeepCopy() *AgentProposalPlan {
	if in == nil {
		return nil
	}
	out := new(AgentProposalPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentProposalSpec) DeepCopyInto(out *AgentProposalSpec) {
	*out = *in
	if in.Evidence != nil {
		in, out := &in.Evidence, &out.Evidence
		*out = new(AgentProposalEvidence)
		(*in).DeepCopyInto(*out)
	}
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(AgentProposalPlan)
		**out = **in
	}
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentProposalSpec.
func (in *AgentProposalSpec) DeepCopy() *AgentProposalSpec {
	if in == nil {
		return nil
	}
	out := new(AgentProposalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentProposalStatus) DeepCopyInto(out *AgentProposalStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ApprovedAt != nil {
		in, out := &in.ApprovedAt, &out.ApprovedAt
		*out = (*in).DeepCopy()
	}
	if in.ResolvedAt != nil {
		in, out := &in.ResolvedAt, &out.ResolvedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentProposalStatus.
func (in *AgentProposalStatus) DeepCopy() *AgentProposalStatus {
	if in == nil {
		return nil
	}
	out := new(AgentProposalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEventSink) DeepCopyInto(out *CloudEventSink) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEventSink.
func (in *CloudEventSink) DeepCopy() *CloudEventSink {
	if in == nil {
		return nil
	}
	out := new(CloudEventSink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudEventSink) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEventSinkList) DeepCopyInto(out *CloudEventSinkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudEventSink, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEventSinkList.
func (in *CloudEventSinkList) DeepCopy() *CloudEventSinkList {
	if in == nil {
		return nil
	}
	out := new(CloudEventSinkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudEventSinkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEventSinkSpec) DeepCopyInto(out *CloudEventSinkSpec) {
	*out = *in
	if in.TypeFilter != nil {
		in, out := &in.TypeFilter, &out.TypeFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AuthSecretRef != nil {
		in, out := &in.AuthSecretRef, &out.AuthSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEventSinkSpec.
func (in *CloudEventSinkSpec) DeepCopy() *CloudEventSinkSpec {
	if in == nil {
		return nil
	}
	out := new(CloudEventSinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEventSinkStatus) DeepCopyInto(out *CloudEventSinkStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastDeliveryTime != nil {
		in, out := &in.LastDeliveryTime, &out.LastDeliveryTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEventSinkStatus.
func (in *CloudEventSinkStatus) DeepCopy() *CloudEventSinkStatus {
	if in == nil {
		return nil
	}
	out := new(CloudEventSinkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Companion) DeepCopyInto(out *Companion) {
	*out = *in
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(CompanionRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Companion.
func (in *Companion) DeepCopy() *Companion {
	if in == nil {
		return nil
	}
	out := new(Companion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompanionConfigMapRef) DeepCopyInto(out *CompanionConfigMapRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompanionConfigMapRef.
func (in *CompanionConfigMapRef) DeepCopy() *CompanionConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(CompanionConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompanionRef) DeepCopyInto(out *CompanionRef) {
	*out = *in
	out.ConfigMap = in.ConfigMap
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompanionRef.
func (in *CompanionRef) DeepCopy() *CompanionRef {
	if in == nil {
		return nil
	}
	out := new(CompanionRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompanionStatus) DeepCopyInto(out *CompanionStatus) {
	*out = *in
	if in.LastAppliedAt != nil {
		in, out := &in.LastAppliedAt, &out.LastAppliedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompanionStatus.
func (in *CompanionStatus) DeepCopy() *CompanionStatus {
	if in == nil {
		return nil
	}
	out := new(CompanionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventDeclaration) DeepCopyInto(out *EventDeclaration) {
	*out = *in
	if in.Payload != nil {
		in, out := &in.Payload, &out.Payload
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventDeclaration.
func (in *EventDeclaration) DeepCopy() *EventDeclaration {
	if in == nil {
		return nil
	}
	out := new(EventDeclaration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromiseBundle) DeepCopyInto(out *PromiseBundle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromiseBundle.
func (in *PromiseBundle) DeepCopy() *PromiseBundle {
	if in == nil {
		return nil
	}
	out := new(PromiseBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PromiseBundle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromiseBundleList) DeepCopyInto(out *PromiseBundleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PromiseBundle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromiseBundleList.
func (in *PromiseBundleList) DeepCopy() *PromiseBundleList {
	if in == nil {
		return nil
	}
	out := new(PromiseBundleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PromiseBundleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromiseBundlePromiseRef) DeepCopyInto(out *PromiseBundlePromiseRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromiseBundlePromiseRef.
func (in *PromiseBundlePromiseRef) DeepCopy() *PromiseBundlePromiseRef {
	if in == nil {
		return nil
	}
	out := new(PromiseBundlePromiseRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromiseBundleSpec) DeepCopyInto(out *PromiseBundleSpec) {
	*out = *in
	out.PromiseRef = in.PromiseRef
	if in.Companions != nil {
		in, out := &in.Companions, &out.Companions
		*out = make([]Companion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromiseBundleSpec.
func (in *PromiseBundleSpec) DeepCopy() *PromiseBundleSpec {
	if in == nil {
		return nil
	}
	out := new(PromiseBundleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromiseBundleStatus) DeepCopyInto(out *PromiseBundleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Companions != nil {
		in, out := &in.Companions, &out.Companions
		*out = make([]CompanionStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromiseBundleStatus.
func (in *PromiseBundleStatus) DeepCopy() *PromiseBundleStatus {
	if in == nil {
		return nil
	}
	out := new(PromiseBundleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromiseSignals) DeepCopyInto(out *PromiseSignals) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromiseSignals.
func (in *PromiseSignals) DeepCopy() *PromiseSignals {
	if in == nil {
		return nil
	}
	out := new(PromiseSignals)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PromiseSignals) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromiseSignalsList) DeepCopyInto(out *PromiseSignalsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PromiseSignals, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromiseSignalsList.
func (in *PromiseSignalsList) DeepCopy() *PromiseSignalsList {
	if in == nil {
		return nil
	}
	out := new(PromiseSignalsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PromiseSignalsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromiseSignalsPromiseRef) DeepCopyInto(out *PromiseSignalsPromiseRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromiseSignalsPromiseRef.
func (in *PromiseSignalsPromiseRef) DeepCopy() *PromiseSignalsPromiseRef {
	if in == nil {
		return nil
	}
	out := new(PromiseSignalsPromiseRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromiseSignalsSpec) DeepCopyInto(out *PromiseSignalsSpec) {
	*out = *in
	out.PromiseRef = in.PromiseRef
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]EventDeclaration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromiseSignalsSpec.
func (in *PromiseSignalsSpec) DeepCopy() *PromiseSignalsSpec {
	if in == nil {
		return nil
	}
	out := new(PromiseSignalsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromiseSignalsStatus) DeepCopyInto(out *PromiseSignalsStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromiseSignalsStatus.
func (in *PromiseSignalsStatus) DeepCopy() *PromiseSignalsStatus {
	if in == nil {
		return nil
	}
	out := new(PromiseSignalsStatus)
	in.DeepCopyInto(out)
	return out
}
