// Code generated by counterfeiter. DO NOT EDIT.
package dispatchfakes

import (
	"context"
	"sync"

	"github.com/syntasso/kratix/lib/writers/dispatch"
)

type FakeBackend struct {
	ApplyBatchStub        func(context.Context, []dispatch.ResolvedIntent) dispatch.BatchResult
	applyBatchMutex       sync.RWMutex
	applyBatchArgsForCall []struct {
		arg1 context.Context
		arg2 []dispatch.ResolvedIntent
	}
	applyBatchReturns struct {
		result1 dispatch.BatchResult
	}
	applyBatchReturnsOnCall map[int]struct {
		result1 dispatch.BatchResult
	}
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	ReadStub        func(context.Context, []string) (map[string][]byte, error)
	readMutex       sync.RWMutex
	readArgsForCall []struct {
		arg1 context.Context
		arg2 []string
	}
	readReturns struct {
		result1 map[string][]byte
		result2 error
	}
	readReturnsOnCall map[int]struct {
		result1 map[string][]byte
		result2 error
	}
	ValidateStub        func(context.Context) error
	validateMutex       sync.RWMutex
	validateArgsForCall []struct {
		arg1 context.Context
	}
	validateReturns struct {
		result1 error
	}
	validateReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBackend) ApplyBatch(arg1 context.Context, arg2 []dispatch.ResolvedIntent) dispatch.BatchResult {
	var arg2Copy []dispatch.ResolvedIntent
	if arg2 != nil {
		arg2Copy = make([]dispatch.ResolvedIntent, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.applyBatchMutex.Lock()
	ret, specificReturn := fake.applyBatchReturnsOnCall[len(fake.applyBatchArgsForCall)]
	fake.applyBatchArgsForCall = append(fake.applyBatchArgsForCall, struct {
		arg1 context.Context
		arg2 []dispatch.ResolvedIntent
	}{arg1, arg2Copy})
	stub := fake.ApplyBatchStub
	fakeReturns := fake.applyBatchReturns
	fake.recordInvocation("ApplyBatch", []interface{}{arg1, arg2Copy})
	fake.applyBatchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBackend) ApplyBatchCallCount() int {
	fake.applyBatchMutex.RLock()
	defer fake.applyBatchMutex.RUnlock()
	return len(fake.applyBatchArgsForCall)
}

func (fake *FakeBackend) ApplyBatchCalls(stub func(context.Context, []dispatch.ResolvedIntent) dispatch.BatchResult) {
	fake.applyBatchMutex.Lock()
	defer fake.applyBatchMutex.Unlock()
	fake.ApplyBatchStub = stub
}

func (fake *FakeBackend) ApplyBatchArgsForCall(i int) (context.Context, []dispatch.ResolvedIntent) {
	fake.applyBatchMutex.RLock()
	defer fake.applyBatchMutex.RUnlock()
	argsForCall := fake.applyBatchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBackend) ApplyBatchReturns(result1 dispatch.BatchResult) {
	fake.applyBatchMutex.Lock()
	defer fake.applyBatchMutex.Unlock()
	fake.ApplyBatchStub = nil
	fake.applyBatchReturns = struct {
		result1 dispatch.BatchResult
	}{result1}
}

func (fake *FakeBackend) ApplyBatchReturnsOnCall(i int, result1 dispatch.BatchResult) {
	fake.applyBatchMutex.Lock()
	defer fake.applyBatchMutex.Unlock()
	fake.ApplyBatchStub = nil
	if fake.applyBatchReturnsOnCall == nil {
		fake.applyBatchReturnsOnCall = make(map[int]struct {
			result1 dispatch.BatchResult
		})
	}
	fake.applyBatchReturnsOnCall[i] = struct {
		result1 dispatch.BatchResult
	}{result1}
}

func (fake *FakeBackend) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBackend) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeBackend) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeBackend) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBackend) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBackend) Read(arg1 context.Context, arg2 []string) (map[string][]byte, error) {
	var arg2Copy []string
	if arg2 != nil {
		arg2Copy = make([]string, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.readMutex.Lock()
	ret, specificReturn := fake.readReturnsOnCall[len(fake.readArgsForCall)]
	fake.readArgsForCall = append(fake.readArgsForCall, struct {
		arg1 context.Context
		arg2 []string
	}{arg1, arg2Copy})
	stub := fake.ReadStub
	fakeReturns := fake.readReturns
	fake.recordInvocation("Read", []interface{}{arg1, arg2Copy})
	fake.readMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBackend) ReadCallCount() int {
	fake.readMutex.RLock()
	defer fake.readMutex.RUnlock()
	return len(fake.readArgsForCall)
}

func (fake *FakeBackend) ReadCalls(stub func(context.Context, []string) (map[string][]byte, error)) {
	fake.readMutex.Lock()
	defer fake.readMutex.Unlock()
	fake.ReadStub = stub
}

func (fake *FakeBackend) ReadArgsForCall(i int) (context.Context, []string) {
	fake.readMutex.RLock()
	defer fake.readMutex.RUnlock()
	argsForCall := fake.readArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBackend) ReadReturns(result1 map[string][]byte, result2 error) {
	fake.readMutex.Lock()
	defer fake.readMutex.Unlock()
	fake.ReadStub = nil
	fake.readReturns = struct {
		result1 map[string][]byte
		result2 error
	}{result1, result2}
}

func (fake *FakeBackend) ReadReturnsOnCall(i int, result1 map[string][]byte, result2 error) {
	fake.readMutex.Lock()
	defer fake.readMutex.Unlock()
	fake.ReadStub = nil
	if fake.readReturnsOnCall == nil {
		fake.readReturnsOnCall = make(map[int]struct {
			result1 map[string][]byte
			result2 error
		})
	}
	fake.readReturnsOnCall[i] = struct {
		result1 map[string][]byte
		result2 error
	}{result1, result2}
}

func (fake *FakeBackend) Validate(arg1 context.Context) error {
	fake.validateMutex.Lock()
	ret, specificReturn := fake.validateReturnsOnCall[len(fake.validateArgsForCall)]
	fake.validateArgsForCall = append(fake.validateArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ValidateStub
	fakeReturns := fake.validateReturns
	fake.recordInvocation("Validate", []interface{}{arg1})
	fake.validateMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBackend) ValidateCallCount() int {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	return len(fake.validateArgsForCall)
}

func (fake *FakeBackend) ValidateCalls(stub func(context.Context) error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = stub
}

func (fake *FakeBackend) ValidateArgsForCall(i int) context.Context {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	argsForCall := fake.validateArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeBackend) ValidateReturns(result1 error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = nil
	fake.validateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBackend) ValidateReturnsOnCall(i int, result1 error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = nil
	if fake.validateReturnsOnCall == nil {
		fake.validateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBackend) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.applyBatchMutex.RLock()
	defer fake.applyBatchMutex.RUnlock()
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	fake.readMutex.RLock()
	defer fake.readMutex.RUnlock()
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBackend) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ dispatch.Backend = new(FakeBackend)
