// Code generated by counterfeiter. DO NOT EDIT.
package dispatchfakes

import (
	"context"
	"sync"

	"github.com/syntasso/kratix/api/v1alpha1"
	"github.com/syntasso/kratix/lib/writers/dispatch"
)

type FakeDispatcher struct {
	CleanupStub        func(dispatch.DestinationKey) error
	cleanupMutex       sync.RWMutex
	cleanupArgsForCall []struct {
		arg1 dispatch.DestinationKey
	}
	cleanupReturns struct {
		result1 error
	}
	cleanupReturnsOnCall map[int]struct {
		result1 error
	}
	RegisterGitDestinationStub        func(dispatch.DestinationKey, v1alpha1.GitStateStoreSpec, map[string][]byte) error
	registerGitDestinationMutex       sync.RWMutex
	registerGitDestinationArgsForCall []struct {
		arg1 dispatch.DestinationKey
		arg2 v1alpha1.GitStateStoreSpec
		arg3 map[string][]byte
	}
	registerGitDestinationReturns struct {
		result1 error
	}
	registerGitDestinationReturnsOnCall map[int]struct {
		result1 error
	}
	RegisterS3DestinationStub        func(dispatch.DestinationKey, v1alpha1.BucketStateStoreSpec, map[string][]byte) error
	registerS3DestinationMutex       sync.RWMutex
	registerS3DestinationArgsForCall []struct {
		arg1 dispatch.DestinationKey
		arg2 v1alpha1.BucketStateStoreSpec
		arg3 map[string][]byte
	}
	registerS3DestinationReturns struct {
		result1 error
	}
	registerS3DestinationReturnsOnCall map[int]struct {
		result1 error
	}
	ShutdownStub        func(context.Context) error
	shutdownMutex       sync.RWMutex
	shutdownArgsForCall []struct {
		arg1 context.Context
	}
	shutdownReturns struct {
		result1 error
	}
	shutdownReturnsOnCall map[int]struct {
		result1 error
	}
	SubmitStub        func(context.Context, dispatch.DestinationKey, dispatch.Intent) (dispatch.Result, error)
	submitMutex       sync.RWMutex
	submitArgsForCall []struct {
		arg1 context.Context
		arg2 dispatch.DestinationKey
		arg3 dispatch.Intent
	}
	submitReturns struct {
		result1 dispatch.Result
		result2 error
	}
	submitReturnsOnCall map[int]struct {
		result1 dispatch.Result
		result2 error
	}
	ValidateStub        func(context.Context, dispatch.DestinationKey) error
	validateMutex       sync.RWMutex
	validateArgsForCall []struct {
		arg1 context.Context
		arg2 dispatch.DestinationKey
	}
	validateReturns struct {
		result1 error
	}
	validateReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDispatcher) Cleanup(arg1 dispatch.DestinationKey) error {
	fake.cleanupMutex.Lock()
	ret, specificReturn := fake.cleanupReturnsOnCall[len(fake.cleanupArgsForCall)]
	fake.cleanupArgsForCall = append(fake.cleanupArgsForCall, struct {
		arg1 dispatch.DestinationKey
	}{arg1})
	stub := fake.CleanupStub
	fakeReturns := fake.cleanupReturns
	fake.recordInvocation("Cleanup", []interface{}{arg1})
	fake.cleanupMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDispatcher) CleanupCallCount() int {
	fake.cleanupMutex.RLock()
	defer fake.cleanupMutex.RUnlock()
	return len(fake.cleanupArgsForCall)
}

func (fake *FakeDispatcher) CleanupCalls(stub func(dispatch.DestinationKey) error) {
	fake.cleanupMutex.Lock()
	defer fake.cleanupMutex.Unlock()
	fake.CleanupStub = stub
}

func (fake *FakeDispatcher) CleanupArgsForCall(i int) dispatch.DestinationKey {
	fake.cleanupMutex.RLock()
	defer fake.cleanupMutex.RUnlock()
	argsForCall := fake.cleanupArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDispatcher) CleanupReturns(result1 error) {
	fake.cleanupMutex.Lock()
	defer fake.cleanupMutex.Unlock()
	fake.CleanupStub = nil
	fake.cleanupReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDispatcher) CleanupReturnsOnCall(i int, result1 error) {
	fake.cleanupMutex.Lock()
	defer fake.cleanupMutex.Unlock()
	fake.CleanupStub = nil
	if fake.cleanupReturnsOnCall == nil {
		fake.cleanupReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.cleanupReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeDispatcher) RegisterGitDestination(arg1 dispatch.DestinationKey, arg2 v1alpha1.GitStateStoreSpec, arg3 map[string][]byte) error {
	fake.registerGitDestinationMutex.Lock()
	ret, specificReturn := fake.registerGitDestinationReturnsOnCall[len(fake.registerGitDestinationArgsForCall)]
	fake.registerGitDestinationArgsForCall = append(fake.registerGitDestinationArgsForCall, struct {
		arg1 dispatch.DestinationKey
		arg2 v1alpha1.GitStateStoreSpec
		arg3 map[string][]byte
	}{arg1, arg2, arg3})
	stub := fake.RegisterGitDestinationStub
	fakeReturns := fake.registerGitDestinationReturns
	fake.recordInvocation("RegisterGitDestination", []interface{}{arg1, arg2, arg3})
	fake.registerGitDestinationMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDispatcher) RegisterGitDestinationCallCount() int {
	fake.registerGitDestinationMutex.RLock()
	defer fake.registerGitDestinationMutex.RUnlock()
	return len(fake.registerGitDestinationArgsForCall)
}

func (fake *FakeDispatcher) RegisterGitDestinationCalls(stub func(dispatch.DestinationKey, v1alpha1.GitStateStoreSpec, map[string][]byte) error) {
	fake.registerGitDestinationMutex.Lock()
	defer fake.registerGitDestinationMutex.Unlock()
	fake.RegisterGitDestinationStub = stub
}

func (fake *FakeDispatcher) RegisterGitDestinationArgsForCall(i int) (dispatch.DestinationKey, v1alpha1.GitStateStoreSpec, map[string][]byte) {
	fake.registerGitDestinationMutex.RLock()
	defer fake.registerGitDestinationMutex.RUnlock()
	argsForCall := fake.registerGitDestinationArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeDispatcher) RegisterGitDestinationReturns(result1 error) {
	fake.registerGitDestinationMutex.Lock()
	defer fake.registerGitDestinationMutex.Unlock()
	fake.RegisterGitDestinationStub = nil
	fake.registerGitDestinationReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDispatcher) RegisterGitDestinationReturnsOnCall(i int, result1 error) {
	fake.registerGitDestinationMutex.Lock()
	defer fake.registerGitDestinationMutex.Unlock()
	fake.RegisterGitDestinationStub = nil
	if fake.registerGitDestinationReturnsOnCall == nil {
		fake.registerGitDestinationReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.registerGitDestinationReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeDispatcher) RegisterS3Destination(arg1 dispatch.DestinationKey, arg2 v1alpha1.BucketStateStoreSpec, arg3 map[string][]byte) error {
	fake.registerS3DestinationMutex.Lock()
	ret, specificReturn := fake.registerS3DestinationReturnsOnCall[len(fake.registerS3DestinationArgsForCall)]
	fake.registerS3DestinationArgsForCall = append(fake.registerS3DestinationArgsForCall, struct {
		arg1 dispatch.DestinationKey
		arg2 v1alpha1.BucketStateStoreSpec
		arg3 map[string][]byte
	}{arg1, arg2, arg3})
	stub := fake.RegisterS3DestinationStub
	fakeReturns := fake.registerS3DestinationReturns
	fake.recordInvocation("RegisterS3Destination", []interface{}{arg1, arg2, arg3})
	fake.registerS3DestinationMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDispatcher) RegisterS3DestinationCallCount() int {
	fake.registerS3DestinationMutex.RLock()
	defer fake.registerS3DestinationMutex.RUnlock()
	return len(fake.registerS3DestinationArgsForCall)
}

func (fake *FakeDispatcher) RegisterS3DestinationCalls(stub func(dispatch.DestinationKey, v1alpha1.BucketStateStoreSpec, map[string][]byte) error) {
	fake.registerS3DestinationMutex.Lock()
	defer fake.registerS3DestinationMutex.Unlock()
	fake.RegisterS3DestinationStub = stub
}

func (fake *FakeDispatcher) RegisterS3DestinationArgsForCall(i int) (dispatch.DestinationKey, v1alpha1.BucketStateStoreSpec, map[string][]byte) {
	fake.registerS3DestinationMutex.RLock()
	defer fake.registerS3DestinationMutex.RUnlock()
	argsForCall := fake.registerS3DestinationArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeDispatcher) RegisterS3DestinationReturns(result1 error) {
	fake.registerS3DestinationMutex.Lock()
	defer fake.registerS3DestinationMutex.Unlock()
	fake.RegisterS3DestinationStub = nil
	fake.registerS3DestinationReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDispatcher) RegisterS3DestinationReturnsOnCall(i int, result1 error) {
	fake.registerS3DestinationMutex.Lock()
	defer fake.registerS3DestinationMutex.Unlock()
	fake.RegisterS3DestinationStub = nil
	if fake.registerS3DestinationReturnsOnCall == nil {
		fake.registerS3DestinationReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.registerS3DestinationReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeDispatcher) Shutdown(arg1 context.Context) error {
	fake.shutdownMutex.Lock()
	ret, specificReturn := fake.shutdownReturnsOnCall[len(fake.shutdownArgsForCall)]
	fake.shutdownArgsForCall = append(fake.shutdownArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ShutdownStub
	fakeReturns := fake.shutdownReturns
	fake.recordInvocation("Shutdown", []interface{}{arg1})
	fake.shutdownMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDispatcher) ShutdownCallCount() int {
	fake.shutdownMutex.RLock()
	defer fake.shutdownMutex.RUnlock()
	return len(fake.shutdownArgsForCall)
}

func (fake *FakeDispatcher) ShutdownCalls(stub func(context.Context) error) {
	fake.shutdownMutex.Lock()
	defer fake.shutdownMutex.Unlock()
	fake.ShutdownStub = stub
}

func (fake *FakeDispatcher) ShutdownArgsForCall(i int) context.Context {
	fake.shutdownMutex.RLock()
	defer fake.shutdownMutex.RUnlock()
	argsForCall := fake.shutdownArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDispatcher) ShutdownReturns(result1 error) {
	fake.shutdownMutex.Lock()
	defer fake.shutdownMutex.Unlock()
	fake.ShutdownStub = nil
	fake.shutdownReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDispatcher) ShutdownReturnsOnCall(i int, result1 error) {
	fake.shutdownMutex.Lock()
	defer fake.shutdownMutex.Unlock()
	fake.ShutdownStub = nil
	if fake.shutdownReturnsOnCall == nil {
		fake.shutdownReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.shutdownReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeDispatcher) Submit(arg1 context.Context, arg2 dispatch.DestinationKey, arg3 dispatch.Intent) (dispatch.Result, error) {
	fake.submitMutex.Lock()
	ret, specificReturn := fake.submitReturnsOnCall[len(fake.submitArgsForCall)]
	fake.submitArgsForCall = append(fake.submitArgsForCall, struct {
		arg1 context.Context
		arg2 dispatch.DestinationKey
		arg3 dispatch.Intent
	}{arg1, arg2, arg3})
	stub := fake.SubmitStub
	fakeReturns := fake.submitReturns
	fake.recordInvocation("Submit", []interface{}{arg1, arg2, arg3})
	fake.submitMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDispatcher) SubmitCallCount() int {
	fake.submitMutex.RLock()
	defer fake.submitMutex.RUnlock()
	return len(fake.submitArgsForCall)
}

func (fake *FakeDispatcher) SubmitCalls(stub func(context.Context, dispatch.DestinationKey, dispatch.Intent) (dispatch.Result, error)) {
	fake.submitMutex.Lock()
	defer fake.submitMutex.Unlock()
	fake.SubmitStub = stub
}

func (fake *FakeDispatcher) SubmitArgsForCall(i int) (context.Context, dispatch.DestinationKey, dispatch.Intent) {
	fake.submitMutex.RLock()
	defer fake.submitMutex.RUnlock()
	argsForCall := fake.submitArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeDispatcher) SubmitReturns(result1 dispatch.Result, result2 error) {
	fake.submitMutex.Lock()
	defer fake.submitMutex.Unlock()
	fake.SubmitStub = nil
	fake.submitReturns = struct {
		result1 dispatch.Result
		result2 error
	}{result1, result2}
}

func (fake *FakeDispatcher) SubmitReturnsOnCall(i int, result1 dispatch.Result, result2 error) {
	fake.submitMutex.Lock()
	defer fake.submitMutex.Unlock()
	fake.SubmitStub = nil
	if fake.submitReturnsOnCall == nil {
		fake.submitReturnsOnCall = make(map[int]struct {
			result1 dispatch.Result
			result2 error
		})
	}
	fake.submitReturnsOnCall[i] = struct {
		result1 dispatch.Result
		result2 error
	}{result1, result2}
}

func (fake *FakeDispatcher) Validate(arg1 context.Context, arg2 dispatch.DestinationKey) error {
	fake.validateMutex.Lock()
	ret, specificReturn := fake.validateReturnsOnCall[len(fake.validateArgsForCall)]
	fake.validateArgsForCall = append(fake.validateArgsForCall, struct {
		arg1 context.Context
		arg2 dispatch.DestinationKey
	}{arg1, arg2})
	stub := fake.ValidateStub
	fakeReturns := fake.validateReturns
	fake.recordInvocation("Validate", []interface{}{arg1, arg2})
	fake.validateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDispatcher) ValidateCallCount() int {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	return len(fake.validateArgsForCall)
}

func (fake *FakeDispatcher) ValidateCalls(stub func(context.Context, dispatch.DestinationKey) error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = stub
}

func (fake *FakeDispatcher) ValidateArgsForCall(i int) (context.Context, dispatch.DestinationKey) {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	argsForCall := fake.validateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeDispatcher) ValidateReturns(result1 error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = nil
	fake.validateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDispatcher) ValidateReturnsOnCall(i int, result1 error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = nil
	if fake.validateReturnsOnCall == nil {
		fake.validateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeDispatcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDispatcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ dispatch.Dispatcher = new(FakeDispatcher)
