name: Test Kratix

on:
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    uses: syntasso/ci/.github/workflows/test-kratix.yaml@main
    with:
      sha: ${{ github.event.pull_request.head.sha }}
      message: ${{ github.event.pull_request.title }}
