on:
  workflow_run:
    workflows: [Test Kratix]
    types: [completed]
    branches: [main]

jobs:
  build-and-push-kratix-platform:
    runs-on: ubuntu-latest
    steps:
      - name: Check out kratix
        uses: actions/checkout@v4
      - name: Docker login to GHCR
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Kratix Platform
        run: |
          make docker-build-and-push
  build-and-push-pipeline-adapter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out kratix
        uses: actions/checkout@v4
      - name: Docker login to GHCR
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Pipeline
        run: |
          make build-and-push-work-creator
