name: Trigger CI
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - '.circleci/**'
      - 'demo/**'
      - '*.md'
      - 'LICENSE.txt'
      - 'PROJECT'
      - '.gitignore'
      - '.golangci-required.yml'
      - '.golangci.yml'
      - '.goreleaser.yaml'
      - '.images'

jobs:
  update-release-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
      - name: Trigger CI with latest commit details
        if: ${{ !env.ACT }}
        run: |
          set -x

          GITHUB_MESSAGE=$(cat <<EOF
          ${{ github.event.head_commit.message }}
          EOF)
          author="${{ github.event.head_commit.author.username }}"
          coauthor="${{ github.event.head_commit.committer.username }}"

          if [ -n "${coauthor}" ] && [ "${author}" != "${coauthor}" ]; then
            author="${author}/${coauthor}"
          fi

          if [ -z "$GITHUB_SHA" ]; then
            GITHUB_SHA=$(git rev-parse HEAD)
            GITHUB_MESSAGE="$(git log --format=%B -n 1 ${GITHUB_SHA})"
            author=${{ github.actor }}
          fi

          gh workflow run \
            --repo syntasso/ci "Kratix" \
            --field sha=$GITHUB_SHA \
            --field message=$GITHUB_MESSAGE \
            --field author=${author} \
            --field shortSHA=${GITHUB_SHA:0:7}
        env:
          GH_TOKEN: ${{ secrets.GH_ACTION_TRIGGER_TOKEN }}
